---

- include: nexus.yml

- name: ANSISTRANO | nexus_unarchive | Set archived file
  set_fact:
    ansistrano_archived_file: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_nexus_artifact_id }}-{{ release_version }}.{{ ansistrano_nexus_extension }}"

- include: unarchive.yml
